Physics= input ("Enter Physics Marks:")
Chemistry= input ("Enter Chemistry Marks:")
Mathematics= input ("Enter Mathematics Marks:")
Total= int (Physics)+ int (Chemistry)+ int (Mathematics)
Per= Total*100/850
print()
print("Physics: ",Physics)
print("Chemistry: ",Chemistry)
print("Mathematics: ",Mathematics)
print()
print("--------------------")
print()
print("Total: ",Total)
print()
print("--------------------")
print()
print("Percentage: ",Per,"%")
